es-models/case_centric/case_centric.mapping.yaml, es-models/gdc_from_graph/annotation.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
Applied new ES mapping in Collab, used the new indexes for a few days. No known problems caused by the pruning, so it should be safe to merge.
=> First pass of ES optimization

es-models/case_set/case_set.mapping.yaml, es-models/case_set/settings.yaml, es-models/file_set/file_set.mapping.yaml, es-models/file_set/settings.yaml, es-models/gene_set/gene_set.mapping.yaml, es-models/gene_set/settings.yaml, es-models/ssm_set/settings.yaml, es-models/ssm_set/ssm_set.mapping.yaml
I have no idea what I'm doing :D any chance it's remotely correct @junjun-zhang @shanewilson
=> PRTL-1279 mappings for save sets

.travis.yml, es-models/case_centric/case_centric.mapping.yaml, es-models/case_centric/settings.yaml, es-models/gdc_from_graph/annotation.mapping.yaml, es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml, es-models/gdc_from_graph/project.mapping.yaml, es-models/gdc_from_graph/settings.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/gene_centric/settings.yaml, es-models/ssm_centric/settings.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/settings.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml, scripts/git-hooks/pre-commit, setup.sh
=> Feature: always sort YAML

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml
See all dictionary changes took place here:
https://github.com/NCI-GDC/gdcdictionary/commit/55f0c237aa1f409919cb947a28e6cb074e33021c#diff-4697dce8e4132dfaf06541ed39b26ae8L2
=> feat(release): Elephant-Cat release data changes

es-models/case_centric/case_centric.mapping.yaml, es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
- new fields from Horton dictionary changes
- `days_to_treatment` removed, as of Horton dictionary
=> Gack release

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml
Relates to https://jira.opensciencedatacloud.org/browse/PRTL-2109
=> Removed file_state field

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml
Adds file version and data_release fields mappings to files and case
=> feat(release_number): added version and release number fields

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml
=> [fix][API-530]: Revert "feat(release_number): added version and release number fields"

es-models/case_centric/case_centric.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
_size, days_to_birth, days_to_death, days_to_treatment, vital_status
This is needed for Jibboo an addresses this ticket: https://jira.opensciencedatacloud.org/browse/TT-804
=> chore(mappings): Added new fields to mappings

es-models/case_centric/case_centric.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
Remove days_to_treatment from all indices (TT-417).
Make vital_status a keyword rather than a free-text field.
Also fixes the "show non-null Case filters" bug in production.
=> fix(mappings): fix issues noted in lorax/jibboo

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml
* update mappings to reflect changes in dictionary
=> fix gdc-models for marvin

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml
This reverts commit 77d0e6c56853b89ff9f4b1751fb1b509d5040f71.
=> Revert "fix gdc-models for marvin"

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml
This reverts commit 0acb4fe8b14a266bb67bcb63ae596a6dcf3ac36f.
=> Revert "Revert "fix gdc-models for marvin""

es-models/case_centric/case_centric.mapping.yaml, es-models/cnv_centric/cnv_centric.mapping.yaml, es-models/cnv_occurrence_centric/cnv_occurrence_centric.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
Add case properties with new values in CPTAC-3 to visualization mappings. Allow indexing of Oobleck case data.
=> fix(viz): add oobleck case properties

es-models/case_centric/case_centric.mapping.yaml, es-models/cnv_centric/cnv_centric.mapping.yaml, es-models/cnv_occurrence_centric/cnv_occurrence_centric.mapping.yaml, es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
move fields from diagnosis to demographic
=> fix(demo): diagnosis fields to demographic

es-models/case_centric/case_centric.mapping.yaml, es-models/cnv_centric/cnv_centric.mapping.yaml, es-models/cnv_occurrence_centric/cnv_occurrence_centric.mapping.yaml, es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
I think we don't need any further changes for Pinwheel. Time to merge this and move the tag back to master?
=> release(pinwheel)

es-models/case_centric/case_centric.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
* administrative, we should use release//* branches instead of merging into master directly*
Reverts NCI-GDC/gdc-models#90
=> Revert "feat(civic): civic clinic annotation"

gdcmodels/__init__.py, tests/conftest.py, tests/test_es_models.py
*administrative, we should use release/* branches instead of merging into master directly*
Reverts NCI-GDC/gdc-models#98
=> Revert "Feat/dat 2384 save es builds output final mappings in gdc models"

es-models/gdc_legacy_graph/case.mapping.yaml, es-models/gdc_legacy_graph/file.mapping.yaml
minimal `follow_ups` struct for legacy.
=> add minimal follow_ups and molecular_test struct

es-models/case_centric/case_centric.mapping.yaml, es-models/cnv_centric/cnv_centric.mapping.yaml, es-models/cnv_occurrence_centric/cnv_occurrence_centric.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml, setup.py
I'll make another one for master after we've moved gdcapi to 2.2.0 and verified that nothing weird happens.
=> release/2.2.0 -> develop

.pre-commit-config.yaml, .secrets.baseline, README.md, dev-requirements.in, dev-requirements.txt, es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/descriptions.yaml, es-models/gdc_from_graph/file.mapping.yaml
Replaces https://github.com/NCI-GDC/gdc-models/pull/140.
=> Sync develop to DAVE-CA Phase 2

es-models/case_centric/case_centric.mapping.yaml, es-models/cnv_centric/cnv_centric.mapping.yaml, es-models/cnv_occurrence_centric/cnv_occurrence_centric.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
Syncing graph and viz mappings with fields that have values as of DR26.
=> DEV-382: add clinical fields with data to viz mappings

es-models/case_centric/case_centric.mapping.yaml, es-models/cnv_centric/cnv_centric.mapping.yaml, es-models/cnv_occurrence_centric/cnv_occurrence_centric.mapping.yaml, es-models/gene_centric/gene_centric.mapping.yaml, es-models/gene_expression/settings.yaml, es-models/ssm_centric/ssm_centric.mapping.yaml, es-models/ssm_occurrence_centric/ssm_occurrence_centric.mapping.yaml
Merge in-progress changes from Nixie Knox release branch to develop. We should probably wait for https://github.com/NCI-GDC/gdc-models/pull/158 to go in first.
=> release/nixie-knox -> develop

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/file.mapping.yaml, es-models/gdc_from_graph/settings.yaml
=> DEV-239 update gdc_from_graph

es-models/gdc_from_graph/settings.yaml, tests/test_init_index.py
- add extra test for that setting
=> DEV-500 increase max_terms_counts for saved sets

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/descriptions.yaml, es-models/gdc_from_graph/file.mapping.yaml
https://jira.opensciencedatacloud.org/browse/DEV-653
=> masked_methylation_array should appear in ES index

es-models/gdc_from_graph/case.mapping.yaml, es-models/gdc_from_graph/descriptions.yaml, es-models/gdc_from_graph/file.mapping.yaml
Update gdc_from_graph mappings to include boveri dictionary changes
=> feat(mappings): update es mappings to boveri release

es-models/case_centric/case_centric.mapping.yaml
These changes add the missing clinical data to the case centric model.
=> DEV-1267: Add missing fields to case centric model

.pre-commit-config.yaml, .travis.yml, gdcmodels/__init__.py, gdcmodels/esutils.py, gdcmodels/init_index.py, scripts/git-hooks/pre-commit, tests/test_init_index.py
=> DEV 2007 drop py35

es-models/gene_expression/gene_expression.mapping.yaml, es-models/gene_expression/settings.yaml
Restructure the gene expression model into a flat one each representing a single gene for a given case.
=> DEV-1986: Update gene expression model & settings.
